# Generated by Django 3.2.3 on 2021-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('_short_hash', models.CharField(blank=True, max_length=8, unique=True)),
            ],
        ),
    ]
