# Generated by Django 3.2.3 on 2021-05-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='_short_hash',
            new_name='short_hash',
        ),
    ]
