# Generated by Django 3.2.3 on 2021-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_rename__short_hash_link_short_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short_hash',
            new_name='_short_hash',
        ),
    ]
