# Generated by Django 3.2.3 on 2021-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_rename_short_hash_link__short_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_url',
            field=models.URLField(unique=True),
        ),
    ]
